// Code generated by heddle-gen. DO NOT EDIT.
package example

import (
	"context"
	"encoding/json"

	"github.com/apache/arrow/go/v18/arrow"
	"github.com/apache/arrow/go/v18/arrow/array"
	"github.com/apache/arrow/go/v18/arrow/memory"

	"github.com/galgotech/heddle-lang/pkg/schema"
	"github.com/galgotech/heddle-sdk-go/registry"
	pluginschema "github.com/galgotech/heddle-sdk-go/schema"
)

func RegisterSteps(reg registry.Registry, steps *Steps) error {
	var err error

	err = reg.RegisterResource(registry.ResourceRegistration{
		Name: "d_b",
		Init: func(ctx context.Context, configJSON string) (pluginschema.Resource, error) {
			var cfg map[string]any
			if configJSON != "" {
				if err := json.Unmarshal([]byte(configJSON), &cfg); err != nil {
					return nil, err
				}
			}
			res := &Connection{}
			configBytes, _ := json.Marshal(cfg)
			if len(configBytes) > 0 && string(configBytes) != "null" {
				json.Unmarshal(configBytes, res)
			}
			err := res.Init(ctx)
			return res, err
		},
	})
	if err != nil {
		return err
	}

	err = reg.RegisterStep(registry.StepRegistration{
		Name: "test_producer",
		ConfigSchema: schema.FieldSchema{
			Fields: []schema.Field{

				{Name: "Query", Type: "utf8"},
			},
		},

		InputSchema: schema.FrameSchema{},

		OutputSchema: schema.FrameSchema{
			Columns: []schema.ColumnSchema{

				{Name: "UserID", ArrowType: "int64"},

				{Name: "Country", ArrowType: "utf8"},
			},
		},

		Invoke: func(ctx context.Context, configJSON string, inColumns map[string]arrow.Array) (map[string]arrow.Array, error) {
			var cfg QueryConfig
			if configJSON != "" {
				if err := json.Unmarshal([]byte(configJSON), &cfg); err != nil {
					return nil, err
				}
			}

			inFrame := pluginschema.Void{}

			outBuilder_UserID := array.NewInt64Builder(memory.DefaultAllocator)
			defer outBuilder_UserID.Release()

			outBuilder_Country := array.NewStringBuilder(memory.DefaultAllocator)
			defer outBuilder_Country.Release()

			outFrame := pluginschema.Frame[QueryOutput]{
				Appender: func(item QueryOutput) {

					outBuilder_UserID.Append(item.UserID)

					outBuilder_Country.Append(item.Country)

				},
			}

			// inject resources

			if resInst, err := reg.GetResource("d_b"); err == nil {
				if resType, ok := resInst.(*Connection); ok {
					steps.DB.SetResource(resType)
				}
			}

			err := steps.TestProducer(ctx, cfg, inFrame, outFrame)
			if err != nil {
				return nil, err
			}

			outColumns := make(map[string]arrow.Array)

			outColumns["UserID"] = outBuilder_UserID.NewArray()

			outColumns["Country"] = outBuilder_Country.NewArray()

			return outColumns, nil
		},
	})
	if err != nil {
		return err
	}

	err = reg.RegisterStep(registry.StepRegistration{
		Name: "query",
		ConfigSchema: schema.FieldSchema{
			Fields: []schema.Field{

				{Name: "Query", Type: "utf8"},
			},
		},

		InputSchema: schema.FrameSchema{
			Columns: []schema.ColumnSchema{

				{Name: "UserID", ArrowType: "int64"},
			},
		},

		OutputSchema: schema.FrameSchema{
			Columns: []schema.ColumnSchema{

				{Name: "UserID", ArrowType: "int64"},

				{Name: "Country", ArrowType: "utf8"},
			},
		},

		Invoke: func(ctx context.Context, configJSON string, inColumns map[string]arrow.Array) (map[string]arrow.Array, error) {
			var cfg QueryConfig
			if configJSON != "" {
				if err := json.Unmarshal([]byte(configJSON), &cfg); err != nil {
					return nil, err
				}
			}

			in_UserID := inColumns["UserID"].(*array.Int64)

			inLen := 0

			if in_UserID != nil {
				inLen = in_UserID.Len()
			}

			inFrame := pluginschema.Frame[QueryInput]{
				Iterator: func(yield func(item QueryInput)) error {
					for i := 0; i < inLen; i++ {
						item := QueryInput{

							UserID: in_UserID.Value(i),
						}
						yield(item)
					}
					return nil
				},
			}

			outBuilder_UserID := array.NewInt64Builder(memory.DefaultAllocator)
			defer outBuilder_UserID.Release()

			outBuilder_Country := array.NewStringBuilder(memory.DefaultAllocator)
			defer outBuilder_Country.Release()

			outFrame := pluginschema.Frame[QueryOutput]{
				Appender: func(item QueryOutput) {

					outBuilder_UserID.Append(item.UserID)

					outBuilder_Country.Append(item.Country)

				},
			}

			// inject resources

			if resInst, err := reg.GetResource("d_b"); err == nil {
				if resType, ok := resInst.(*Connection); ok {
					steps.DB.SetResource(resType)
				}
			}

			err := steps.Query(ctx, cfg, inFrame, outFrame)
			if err != nil {
				return nil, err
			}

			outColumns := make(map[string]arrow.Array)

			outColumns["UserID"] = outBuilder_UserID.NewArray()

			outColumns["Country"] = outBuilder_Country.NewArray()

			return outColumns, nil
		},
	})
	if err != nil {
		return err
	}

	return nil
}

func toSnakeCase(s string) string {
	var res []rune
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				res = append(res, '_')
			}
			res = append(res, r+32)
		} else {
			res = append(res, r)
		}
	}
	return string(res)
}
