// Code generated by heddle-gen. DO NOT EDIT.
package example

import (
	"context"
	"encoding/json"

	"github.com/apache/arrow/go/v18/arrow"
	"github.com/apache/arrow/go/v18/arrow/array"
	"github.com/apache/arrow/go/v18/arrow/memory"

	"github.com/galgotech/heddle-lang/pkg/schema"
	"github.com/galgotech/heddle-sdk-go/plugin"
	pluginschema "github.com/galgotech/heddle-sdk-go/schema"
)

func RegisterSteps(p *plugin.Plugin) error {
	globalSteps := &Steps{}
	var err error

	err = p.RegisterResource(plugin.ResourceRegistration{
		Name: "d_b",
		Init: func(ctx context.Context, configJSON string) (pluginschema.Resource, error) {
			var cfg map[string]any
			if configJSON != "" {
				if err := json.Unmarshal([]byte(configJSON), &cfg); err != nil {
					return nil, err
				}
			}
			res := &Connection{}
			configBytes, _ := json.Marshal(cfg)
			if len(configBytes) > 0 && string(configBytes) != "null" {
				json.Unmarshal(configBytes, res)
			}
			err := res.Init(ctx)
			return res, err
		},
	})
	if err != nil {
		return err
	}

	err = p.RegisterStep(plugin.StepRegistration{
		Name: "test_producer",
		ConfigSchema: schema.FieldSchema{
			Fields: []schema.Field{

				{Name: "SQL", Type: "utf8"},
			},
		},

		InputSchema: schema.FrameSchema{},

		OutputSchema: schema.FrameSchema{
			Columns: []schema.ColumnSchema{

				{Name: "UserID", ArrowType: "int64"},

				{Name: "Country", ArrowType: "utf8"},
			},
		},

		Invoke: func(ctx context.Context, configJSON string, inColumns map[string]arrow.Array) (map[string]arrow.Array, error) {
			stepInst := *globalSteps
			if configJSON != "" {
				if err := json.Unmarshal([]byte(configJSON), &stepInst); err != nil {
					return nil, err
				}
			}

			outBuilder_UserID := array.NewInt64Builder(memory.DefaultAllocator)
			defer outBuilder_UserID.Release()

			outBuilder_Country := array.NewStringBuilder(memory.DefaultAllocator)
			defer outBuilder_Country.Release()

			outFrame := pluginschema.FrameOutput[QueryOutput]{
				Appender: func(item QueryOutput) {

					outBuilder_UserID.Append(item.UserID)

					outBuilder_Country.Append(item.Country)

				},
			}

			// inject resources

			if resInst, err := p.Registry().GetResource("d_b"); err == nil {
				if resType, ok := resInst.(*Connection); ok {
					stepInst.DB.SetResource(resType)
				}
			}

			err := stepInst.TestProducer(ctx, outFrame)
			if err != nil {
				return nil, err
			}

			outColumns := make(map[string]arrow.Array)

			outColumns["UserID"] = outBuilder_UserID.NewArray()

			outColumns["Country"] = outBuilder_Country.NewArray()

			return outColumns, nil
		},
	})
	if err != nil {
		return err
	}

	err = p.RegisterStep(plugin.StepRegistration{
		Name: "query",
		ConfigSchema: schema.FieldSchema{
			Fields: []schema.Field{

				{Name: "SQL", Type: "utf8"},
			},
		},

		InputSchema: schema.FrameSchema{
			Columns: []schema.ColumnSchema{

				{Name: "UserID", ArrowType: "int64"},

				{Name: "SubInput", ArrowType: "list"},
			},
		},

		OutputSchema: schema.FrameSchema{
			Columns: []schema.ColumnSchema{

				{Name: "UserID", ArrowType: "int64"},

				{Name: "Country", ArrowType: "utf8"},
			},
		},

		Invoke: func(ctx context.Context, configJSON string, inColumns map[string]arrow.Array) (map[string]arrow.Array, error) {
			stepInst := *globalSteps
			if configJSON != "" {
				if err := json.Unmarshal([]byte(configJSON), &stepInst); err != nil {
					return nil, err
				}
			}

			in_UserID := inColumns["UserID"].(*array.Int64)

			var in_SubInput *array.List
			if col, ok := inColumns["SubInput"]; ok && col != nil {
				in_SubInput = col.(*array.List)
			}

			inLen := 0

			if in_UserID != nil {
				inLen = in_UserID.Len()
			}

			outBuilder__errors := array.NewStringBuilder(memory.DefaultAllocator)
			defer outBuilder__errors.Release()

			inFrame := pluginschema.FrameInput[QueryInput]{
				Iterator: func(yield func(item QueryInput) error) error {
					for i := 0; i < inLen; i++ {

						var nestedFrame_SubInput pluginschema.FrameInput[SubInput]
						if in_SubInput != nil && !in_SubInput.IsNull(i) {
							start := int(in_SubInput.Offsets()[i])
							end := int(in_SubInput.Offsets()[i+1])
							listValues := in_SubInput.ListValues()

							if structArr, ok := listValues.(*array.Struct); ok {

								var l_Name *array.String

								for c := 0; c < structArr.NumField(); c++ {
									field := structArr.DataType().(*arrow.StructType).Field(c)
									colArr := structArr.Field(c)
									switch field.Name {

									case "Name":
										l_Name, _ = colArr.(*array.String)

									}
								}

								nestedFrame_SubInput = pluginschema.FrameInput[SubInput]{
									Iterator: func(y func(m SubInput) error) error {
										for j := start; j < end; j++ {
											m := SubInput{}

											if l_Name != nil && !l_Name.IsNull(j) {
												m.Name = l_Name.Value(j)
											}

											if err := y(m); err != nil {
												itemBytes, _ := json.Marshal(m)
												errorPayload, _ := json.Marshal(map[string]any{"error": err.Error(), "item": json.RawMessage(itemBytes)})
												outBuilder__errors.Append(string(errorPayload))
											}
										}
										return nil
									},
								}

							}
						}

						item := QueryInput{

							UserID: in_UserID.Value(i),

							SubInput: nestedFrame_SubInput,
						}
						if err := yield(item); err != nil {
							itemBytes, _ := json.Marshal(item)
							errorPayload, _ := json.Marshal(map[string]any{"error": err.Error(), "item": json.RawMessage(itemBytes)})
							outBuilder__errors.Append(string(errorPayload))
						}
					}
					return nil
				},
			}

			outBuilder_UserID := array.NewInt64Builder(memory.DefaultAllocator)
			defer outBuilder_UserID.Release()

			outBuilder_Country := array.NewStringBuilder(memory.DefaultAllocator)
			defer outBuilder_Country.Release()

			outFrame := pluginschema.FrameOutput[QueryOutput]{
				Appender: func(item QueryOutput) {

					outBuilder_UserID.Append(item.UserID)

					outBuilder_Country.Append(item.Country)

				},
			}

			// inject resources

			if resInst, err := p.Registry().GetResource("d_b"); err == nil {
				if resType, ok := resInst.(*Connection); ok {
					stepInst.DB.SetResource(resType)
				}
			}

			err := stepInst.Query(ctx, inFrame, outFrame)
			if err != nil {
				return nil, err
			}

			outColumns := make(map[string]arrow.Array)

			outColumns["UserID"] = outBuilder_UserID.NewArray()

			outColumns["Country"] = outBuilder_Country.NewArray()

			if outBuilder__errors.Len() > 0 {
				outColumns["_errors"] = outBuilder__errors.NewArray()
			}

			return outColumns, nil
		},
	})
	if err != nil {
		return err
	}

	return nil
}
